name: autofcm_sdk
description: AutoFCM SDK for in-app modal notifications, FCM handling, and campaign automation
version: 1.1.0

homepage: https://pingautobe.boostproductivity.online/
repository: https://github.com/Lalit-AppSuccessor/AutoFcm-backend

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.2.2
  firebase_messaging: ">=14.0.0 <17.0.0"
  url_launcher: ^6.2.5
  connectivity_plus: ^6.0.3

flutter:
  assets:
    - lib/assets/images/headerLogo.png
    - lib/assets/images/bgClouds.png

dev_dependencies:
  flutter_lints: ^3.0.0
